# Generated by Django 6.0.1 on 2026-01-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stay_type', models.CharField(choices=[('hotel', 'Hotel'), ('guesthouse', 'Guest House'), ('hostel', 'Hostel')], default='hotel', max_length=20)),
                ('city', models.CharField(max_length=120)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
                ('address', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
