# Generated by Django 6.0.1 on 2026-01-16 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='stays/')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='stays.stay')),
            ],
        ),
    ]
