# Generated by Django 6.0.1 on 2026-01-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_staymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='staymedia',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='staymedia',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='staymedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='stays/'),
        ),
    ]
