# Generated by Django 4.2.7 on 2026-03-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0004_booking_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, help_text='السعر الإجمالي باللأوقية (UM)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='stay',
            name='start_price',
            field=models.DecimalField(decimal_places=2, help_text='السعر باللأوقية (UM)', max_digits=15),
        ),
    ]
