# Generated by Django 4.2.11 on 2026-03-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0005_alter_booking_total_price_alter_stay_start_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='latitude',
            field=models.FloatField(blank=True, help_text='خط العرض', null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='longitude',
            field=models.FloatField(blank=True, help_text='خط الطول', null=True),
        ),
    ]
