services:
  - type: web
    name: tourism-platform
    env: python
    region: singapore
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tourism_platform.tourism_platform.wsgi:application --bind 0.0.0.0:8080 --workers 1 --timeout 120
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "django-insecure-j^cb)jmvxcspaf*f4mei4v)jw$0&-77sixd@h+b^*ma^n=2#j*"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: PORT
        value: "8080"