# Generated by Django 6.0.1 on 2026-01-15 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=120)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('languages', models.CharField(help_text='مثال: عربي, English, Français', max_length=200)),
                ('specialties', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GuideReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='guides.guide')),
            ],
        ),
    ]
