# Generated by Django 6.0.1 on 2026-01-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_alter_guidereview_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='guides/')),
                ('url', models.URLField(blank=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='guides.guide')),
            ],
        ),
    ]
